language: nix
script: nix-build dev.nix -A python-moa --arg benchmark true

deploy:
  provider: script
  skip_cleanup: true
  script: >-
    nix-build dev.nix -A release &&
    nix-shell -p python3Packages.twine --run "twine upload result/*"
  on:
    tags: true
